export const ERROR = 'ERROR';
export const UNSET_ERROR = 'UNSET_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const SET_UPDATING_USER_STATUS = 'SET_UPDATING_USER_STATUS';

export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';

export const SET_BRANDS = 'SET_BRANDS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_PRODUCTS = 'SET_PRODUCTS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_ITEM_QUANTITY = 'CHANGE_ITEM_QUANTITY';
export const FILL_CART = 'FILL_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const ORDER_SAVED = 'ORDER_SAVED';

export const SET_CURRENT_USER_ORDERS = 'SET_CURRENT_USER_ORDERS';

export const SET_ALL_ORDERS = 'SET_ALL_ORDERS';
export const SET_ALL_USERS = 'SET_ALL_USERS';
export const SET_ONE_USER_ORDERS = 'SET_ONE_USER_ORDERS';
