export const ERROR = 'ERROR';
export const UNSET_ERROR = 'UNSET_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const SET_UPDATING_USER_STATUS = 'SET_UPDATING_USER_STATUS';

export const SIGN_UP_COMPLETED = 'SIGN_UP_COMPLETED';

export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';

export const SET_BRANDS = 'SET_BRANDS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
